/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as LegalSlugRouteImport } from './routes/legal/$slug'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPaymentMethodsRouteImport } from './routes/admin.payment-methods'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminBroadcastRouteImport } from './routes/admin.broadcast'
import { Route as AdminIgIndexRouteImport } from './routes/admin.ig.index'
import { Route as ApiCronIgCommentsRouteImport } from './routes/api/cron/ig-comments'
import { Route as ApiCronEnsureWebhookRouteImport } from './routes/api/cron/ensure-webhook'
import { Route as ApiCronBroadcastRouteImport } from './routes/api/cron/broadcast'
import { Route as ApiAdminUploadRouteImport } from './routes/api/admin/upload'
import { Route as AdminIgPostsRouteImport } from './routes/admin.ig.posts'
import { Route as AdminIgLogRouteImport } from './routes/admin.ig.log'
import { Route as AdminIgLeadsRouteImport } from './routes/admin.ig.leads'
import { Route as AdminIgKeywordsRouteImport } from './routes/admin.ig.keywords'
import { Route as AdminIgExclusionsRouteImport } from './routes/admin.ig.exclusions'
import { Route as AdminIgAccountRouteImport } from './routes/admin.ig.account'
import { Route as ApiPublicUnipileWebhookRouteImport } from './routes/api/public/unipile/webhook'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicRobokassaSuccessRouteImport } from './routes/api/public/robokassa/success'
import { Route as ApiPublicRobokassaResultRouteImport } from './routes/api/public/robokassa/result'
import { Route as ApiPublicRobokassaFailRouteImport } from './routes/api/public/robokassa/fail'
import { Route as ApiPublicImgSplatRouteImport } from './routes/api/public/img/$'
import { Route as ApiAdminFileSplatRouteImport } from './routes/api/admin/file/$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentMethodsRoute = AdminPaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBroadcastRoute = AdminBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIgIndexRoute = AdminIgIndexRouteImport.update({
  id: '/ig/',
  path: '/ig/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiCronIgCommentsRoute = ApiCronIgCommentsRouteImport.update({
  id: '/api/cron/ig-comments',
  path: '/api/cron/ig-comments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronEnsureWebhookRoute = ApiCronEnsureWebhookRouteImport.update({
  id: '/api/cron/ensure-webhook',
  path: '/api/cron/ensure-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronBroadcastRoute = ApiCronBroadcastRouteImport.update({
  id: '/api/cron/broadcast',
  path: '/api/cron/broadcast',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUploadRoute = ApiAdminUploadRouteImport.update({
  id: '/api/admin/upload',
  path: '/api/admin/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIgPostsRoute = AdminIgPostsRouteImport.update({
  id: '/ig/posts',
  path: '/ig/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIgLogRoute = AdminIgLogRouteImport.update({
  id: '/ig/log',
  path: '/ig/log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIgLeadsRoute = AdminIgLeadsRouteImport.update({
  id: '/ig/leads',
  path: '/ig/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIgKeywordsRoute = AdminIgKeywordsRouteImport.update({
  id: '/ig/keywords',
  path: '/ig/keywords',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIgExclusionsRoute = AdminIgExclusionsRouteImport.update({
  id: '/ig/exclusions',
  path: '/ig/exclusions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIgAccountRoute = AdminIgAccountRouteImport.update({
  id: '/ig/account',
  path: '/ig/account',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicUnipileWebhookRoute = ApiPublicUnipileWebhookRouteImport.update({
  id: '/api/public/unipile/webhook',
  path: '/api/public/unipile/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRobokassaSuccessRoute =
  ApiPublicRobokassaSuccessRouteImport.update({
    id: '/api/public/robokassa/success',
    path: '/api/public/robokassa/success',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRobokassaResultRoute =
  ApiPublicRobokassaResultRouteImport.update({
    id: '/api/public/robokassa/result',
    path: '/api/public/robokassa/result',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRobokassaFailRoute = ApiPublicRobokassaFailRouteImport.update({
  id: '/api/public/robokassa/fail',
  path: '/api/public/robokassa/fail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImgSplatRoute = ApiPublicImgSplatRouteImport.update({
  id: '/api/public/img/$',
  path: '/api/public/img/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminFileSplatRoute = ApiAdminFileSplatRouteImport.update({
  id: '/api/admin/file/$',
  path: '/api/admin/file/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payment-methods': typeof AdminPaymentMethodsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/ig/account': typeof AdminIgAccountRoute
  '/admin/ig/exclusions': typeof AdminIgExclusionsRoute
  '/admin/ig/keywords': typeof AdminIgKeywordsRoute
  '/admin/ig/leads': typeof AdminIgLeadsRoute
  '/admin/ig/log': typeof AdminIgLogRoute
  '/admin/ig/posts': typeof AdminIgPostsRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/api/cron/broadcast': typeof ApiCronBroadcastRoute
  '/api/cron/ensure-webhook': typeof ApiCronEnsureWebhookRoute
  '/api/cron/ig-comments': typeof ApiCronIgCommentsRoute
  '/admin/ig/': typeof AdminIgIndexRoute
  '/api/admin/file/$': typeof ApiAdminFileSplatRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/api/public/robokassa/fail': typeof ApiPublicRobokassaFailRoute
  '/api/public/robokassa/result': typeof ApiPublicRobokassaResultRoute
  '/api/public/robokassa/success': typeof ApiPublicRobokassaSuccessRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/unipile/webhook': typeof ApiPublicUnipileWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payment-methods': typeof AdminPaymentMethodsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/ig/account': typeof AdminIgAccountRoute
  '/admin/ig/exclusions': typeof AdminIgExclusionsRoute
  '/admin/ig/keywords': typeof AdminIgKeywordsRoute
  '/admin/ig/leads': typeof AdminIgLeadsRoute
  '/admin/ig/log': typeof AdminIgLogRoute
  '/admin/ig/posts': typeof AdminIgPostsRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/api/cron/broadcast': typeof ApiCronBroadcastRoute
  '/api/cron/ensure-webhook': typeof ApiCronEnsureWebhookRoute
  '/api/cron/ig-comments': typeof ApiCronIgCommentsRoute
  '/admin/ig': typeof AdminIgIndexRoute
  '/api/admin/file/$': typeof ApiAdminFileSplatRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/api/public/robokassa/fail': typeof ApiPublicRobokassaFailRoute
  '/api/public/robokassa/result': typeof ApiPublicRobokassaResultRoute
  '/api/public/robokassa/success': typeof ApiPublicRobokassaSuccessRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/unipile/webhook': typeof ApiPublicUnipileWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payment-methods': typeof AdminPaymentMethodsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/ig/account': typeof AdminIgAccountRoute
  '/admin/ig/exclusions': typeof AdminIgExclusionsRoute
  '/admin/ig/keywords': typeof AdminIgKeywordsRoute
  '/admin/ig/leads': typeof AdminIgLeadsRoute
  '/admin/ig/log': typeof AdminIgLogRoute
  '/admin/ig/posts': typeof AdminIgPostsRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/api/cron/broadcast': typeof ApiCronBroadcastRoute
  '/api/cron/ensure-webhook': typeof ApiCronEnsureWebhookRoute
  '/api/cron/ig-comments': typeof ApiCronIgCommentsRoute
  '/admin/ig/': typeof AdminIgIndexRoute
  '/api/admin/file/$': typeof ApiAdminFileSplatRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/api/public/robokassa/fail': typeof ApiPublicRobokassaFailRoute
  '/api/public/robokassa/result': typeof ApiPublicRobokassaResultRoute
  '/api/public/robokassa/success': typeof ApiPublicRobokassaSuccessRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/unipile/webhook': typeof ApiPublicUnipileWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/broadcast'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/payment-methods'
    | '/admin/products'
    | '/admin/settings'
    | '/legal/$slug'
    | '/admin/'
    | '/admin/ig/account'
    | '/admin/ig/exclusions'
    | '/admin/ig/keywords'
    | '/admin/ig/leads'
    | '/admin/ig/log'
    | '/admin/ig/posts'
    | '/api/admin/upload'
    | '/api/cron/broadcast'
    | '/api/cron/ensure-webhook'
    | '/api/cron/ig-comments'
    | '/admin/ig/'
    | '/api/admin/file/$'
    | '/api/public/img/$'
    | '/api/public/robokassa/fail'
    | '/api/public/robokassa/result'
    | '/api/public/robokassa/success'
    | '/api/public/telegram/webhook'
    | '/api/public/unipile/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/broadcast'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/payment-methods'
    | '/admin/products'
    | '/admin/settings'
    | '/legal/$slug'
    | '/admin'
    | '/admin/ig/account'
    | '/admin/ig/exclusions'
    | '/admin/ig/keywords'
    | '/admin/ig/leads'
    | '/admin/ig/log'
    | '/admin/ig/posts'
    | '/api/admin/upload'
    | '/api/cron/broadcast'
    | '/api/cron/ensure-webhook'
    | '/api/cron/ig-comments'
    | '/admin/ig'
    | '/api/admin/file/$'
    | '/api/public/img/$'
    | '/api/public/robokassa/fail'
    | '/api/public/robokassa/result'
    | '/api/public/robokassa/success'
    | '/api/public/telegram/webhook'
    | '/api/public/unipile/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/broadcast'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/payment-methods'
    | '/admin/products'
    | '/admin/settings'
    | '/legal/$slug'
    | '/admin/'
    | '/admin/ig/account'
    | '/admin/ig/exclusions'
    | '/admin/ig/keywords'
    | '/admin/ig/leads'
    | '/admin/ig/log'
    | '/admin/ig/posts'
    | '/api/admin/upload'
    | '/api/cron/broadcast'
    | '/api/cron/ensure-webhook'
    | '/api/cron/ig-comments'
    | '/admin/ig/'
    | '/api/admin/file/$'
    | '/api/public/img/$'
    | '/api/public/robokassa/fail'
    | '/api/public/robokassa/result'
    | '/api/public/robokassa/success'
    | '/api/public/telegram/webhook'
    | '/api/public/unipile/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  LegalSlugRoute: typeof LegalSlugRoute
  ApiAdminUploadRoute: typeof ApiAdminUploadRoute
  ApiCronBroadcastRoute: typeof ApiCronBroadcastRoute
  ApiCronEnsureWebhookRoute: typeof ApiCronEnsureWebhookRoute
  ApiCronIgCommentsRoute: typeof ApiCronIgCommentsRoute
  ApiAdminFileSplatRoute: typeof ApiAdminFileSplatRoute
  ApiPublicImgSplatRoute: typeof ApiPublicImgSplatRoute
  ApiPublicRobokassaFailRoute: typeof ApiPublicRobokassaFailRoute
  ApiPublicRobokassaResultRoute: typeof ApiPublicRobokassaResultRoute
  ApiPublicRobokassaSuccessRoute: typeof ApiPublicRobokassaSuccessRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  ApiPublicUnipileWebhookRoute: typeof ApiPublicUnipileWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payment-methods': {
      id: '/admin/payment-methods'
      path: '/payment-methods'
      fullPath: '/admin/payment-methods'
      preLoaderRoute: typeof AdminPaymentMethodsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/broadcast': {
      id: '/admin/broadcast'
      path: '/broadcast'
      fullPath: '/admin/broadcast'
      preLoaderRoute: typeof AdminBroadcastRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ig/': {
      id: '/admin/ig/'
      path: '/ig'
      fullPath: '/admin/ig/'
      preLoaderRoute: typeof AdminIgIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/cron/ig-comments': {
      id: '/api/cron/ig-comments'
      path: '/api/cron/ig-comments'
      fullPath: '/api/cron/ig-comments'
      preLoaderRoute: typeof ApiCronIgCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/ensure-webhook': {
      id: '/api/cron/ensure-webhook'
      path: '/api/cron/ensure-webhook'
      fullPath: '/api/cron/ensure-webhook'
      preLoaderRoute: typeof ApiCronEnsureWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/broadcast': {
      id: '/api/cron/broadcast'
      path: '/api/cron/broadcast'
      fullPath: '/api/cron/broadcast'
      preLoaderRoute: typeof ApiCronBroadcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/upload': {
      id: '/api/admin/upload'
      path: '/api/admin/upload'
      fullPath: '/api/admin/upload'
      preLoaderRoute: typeof ApiAdminUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ig/posts': {
      id: '/admin/ig/posts'
      path: '/ig/posts'
      fullPath: '/admin/ig/posts'
      preLoaderRoute: typeof AdminIgPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ig/log': {
      id: '/admin/ig/log'
      path: '/ig/log'
      fullPath: '/admin/ig/log'
      preLoaderRoute: typeof AdminIgLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ig/leads': {
      id: '/admin/ig/leads'
      path: '/ig/leads'
      fullPath: '/admin/ig/leads'
      preLoaderRoute: typeof AdminIgLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ig/keywords': {
      id: '/admin/ig/keywords'
      path: '/ig/keywords'
      fullPath: '/admin/ig/keywords'
      preLoaderRoute: typeof AdminIgKeywordsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ig/exclusions': {
      id: '/admin/ig/exclusions'
      path: '/ig/exclusions'
      fullPath: '/admin/ig/exclusions'
      preLoaderRoute: typeof AdminIgExclusionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ig/account': {
      id: '/admin/ig/account'
      path: '/ig/account'
      fullPath: '/admin/ig/account'
      preLoaderRoute: typeof AdminIgAccountRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/unipile/webhook': {
      id: '/api/public/unipile/webhook'
      path: '/api/public/unipile/webhook'
      fullPath: '/api/public/unipile/webhook'
      preLoaderRoute: typeof ApiPublicUnipileWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/robokassa/success': {
      id: '/api/public/robokassa/success'
      path: '/api/public/robokassa/success'
      fullPath: '/api/public/robokassa/success'
      preLoaderRoute: typeof ApiPublicRobokassaSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/robokassa/result': {
      id: '/api/public/robokassa/result'
      path: '/api/public/robokassa/result'
      fullPath: '/api/public/robokassa/result'
      preLoaderRoute: typeof ApiPublicRobokassaResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/robokassa/fail': {
      id: '/api/public/robokassa/fail'
      path: '/api/public/robokassa/fail'
      fullPath: '/api/public/robokassa/fail'
      preLoaderRoute: typeof ApiPublicRobokassaFailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/img/$': {
      id: '/api/public/img/$'
      path: '/api/public/img/$'
      fullPath: '/api/public/img/$'
      preLoaderRoute: typeof ApiPublicImgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/file/$': {
      id: '/api/admin/file/$'
      path: '/api/admin/file/$'
      fullPath: '/api/admin/file/$'
      preLoaderRoute: typeof ApiAdminFileSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBroadcastRoute: typeof AdminBroadcastRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentMethodsRoute: typeof AdminPaymentMethodsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminIgAccountRoute: typeof AdminIgAccountRoute
  AdminIgExclusionsRoute: typeof AdminIgExclusionsRoute
  AdminIgKeywordsRoute: typeof AdminIgKeywordsRoute
  AdminIgLeadsRoute: typeof AdminIgLeadsRoute
  AdminIgLogRoute: typeof AdminIgLogRoute
  AdminIgPostsRoute: typeof AdminIgPostsRoute
  AdminIgIndexRoute: typeof AdminIgIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBroadcastRoute: AdminBroadcastRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentMethodsRoute: AdminPaymentMethodsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminIgAccountRoute: AdminIgAccountRoute,
  AdminIgExclusionsRoute: AdminIgExclusionsRoute,
  AdminIgKeywordsRoute: AdminIgKeywordsRoute,
  AdminIgLeadsRoute: AdminIgLeadsRoute,
  AdminIgLogRoute: AdminIgLogRoute,
  AdminIgPostsRoute: AdminIgPostsRoute,
  AdminIgIndexRoute: AdminIgIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  LegalSlugRoute: LegalSlugRoute,
  ApiAdminUploadRoute: ApiAdminUploadRoute,
  ApiCronBroadcastRoute: ApiCronBroadcastRoute,
  ApiCronEnsureWebhookRoute: ApiCronEnsureWebhookRoute,
  ApiCronIgCommentsRoute: ApiCronIgCommentsRoute,
  ApiAdminFileSplatRoute: ApiAdminFileSplatRoute,
  ApiPublicImgSplatRoute: ApiPublicImgSplatRoute,
  ApiPublicRobokassaFailRoute: ApiPublicRobokassaFailRoute,
  ApiPublicRobokassaResultRoute: ApiPublicRobokassaResultRoute,
  ApiPublicRobokassaSuccessRoute: ApiPublicRobokassaSuccessRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  ApiPublicUnipileWebhookRoute: ApiPublicUnipileWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
